name: SDF Autoencoder CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-glx
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .  # Install package in editable mode
        pip install pytest pytest-cov mypy
        echo "Installed Python packages:"
        pip list
    
    - name: Show project structure
      run: |
        echo "Project structure:"
        tree -L 2 || (sudo apt-get install -y tree && tree -L 2)
    
    - name: Run unit tests
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        pytest tests/ -v --tb=long --capture=no

    - name: Type checking
      if: success() || failure()  # Run even if tests fail
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        mypy src/ --strict --show-error-codes

    - name: List test directory contents
      if: failure()
      run: |
        echo "Tests directory contents:"
        ls -R tests/
        
    - name: Show test file contents
      if: failure()
      run: |
        for file in $(find tests/ -name "*.py"); do
          echo "=== Contents of $file ==="
          cat "$file"
          echo "========================="
        done

    - name: Debug imports
      if: failure()
      run: |
        echo "Python path:"
        python -c "import sys; print('\n'.join(sys.path))"
        echo "Trying to import the package:"
        python -c "import src; print('Package imported successfully')"
